# fly.toml app configuration file generated for repoinspector on 2023-09-29T11:49:09+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "repoinspector"
primary_region = "waw"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
