[development.email]
username = "dimm.gd@ukr.net"
password = "ZIIkvNcSPqaGY0jp"
smtp_server = "smtp.ukr.net"
port = 465

[development.db]
sql_url = "postgresql+psycopg2://repo:repo@127.0.0.1:5432/repoinspector_test"

[development.google]
data_client_id = "765613592323-kr0gkq10iblpltsp6b0743clbrqmmkr5.apps.googleusercontent.com"

[development.security]
# openssl rand -hex 32
SECRET_KEY = "499ce98512faa306842159598b598fe6d49112b9c4bd689e681d00e1d1a83c37"
