schema: https://docs.github.com/public/schema.docs.graphql
overwrite: true
documents:
  [
    './src/features/gql/mutations/**/*.(graphql|ts|js)',
    './src/features/gql/queries/**/*.(graphql|ts|js)',
  ]
generates:
  ./src/features/gql/graphql.schema.ts:
    plugins:
      - typescript
      - typescript-operations
