"""Columns for additional statistic added

Revision ID: 9aa6d5120b0b
Revises: ba474f47d3f2
Create Date: 2023-07-25 14:25:52.894086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aa6d5120b0b'
down_revision = 'ba474f47d3f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repository', sa.Column('contributors_count', sa.Integer(), nullable=True))
    op.add_column('repository', sa.Column('issues_count', sa.Integer(), nullable=True))
    op.add_column('repository', sa.Column('pull_requests_count', sa.Integer(), nullable=True))
    op.add_column('repository', sa.Column('pull_requests_merged_ltm', sa.Integer(), nullable=True))
    op.add_column('repository', sa.Column('watchers_count', sa.Integer(), nullable=True))
    op.add_column('repository', sa.Column('health', sa.Integer(), nullable=True))
    op.add_column('repository', sa.Column('issues_opened_ltm', sa.Integer(), nullable=True))
    op.add_column('repository', sa.Column('issues_history', sa.String, nullable=True))
    op.add_column('repository', sa.Column('stars_history', sa.String, nullable=True))
    op.add_column('repository', sa.Column('last_month_stars', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repository', 'last_month_stars')
    op.drop_column('repository', 'stars_history')
    op.drop_column('repository', 'issues_history')
    op.drop_column('repository', 'issues_opened_ltm')
    op.drop_column('repository', 'health')
    op.drop_column('repository', 'watchers_count')
    op.drop_column('repository', 'pull_requests_merged_ltm')
    op.drop_column('repository', 'pull_requests_count')
    op.drop_column('repository', 'issues_count')
    op.drop_column('repository', 'contributors_count')
    # ### end Alembic commands ###
